// Regenerate the <script> block for widgets in index.html from the files in
// src/renderer/widgets/. Keeps widget registration automatic as clusters land.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const wdir = path.join(root, "src/renderer/widgets");
const htmlPath = path.join(root, "src/renderer/index.html");

const files = fs.readdirSync(wdir).filter(f => f.endsWith(".js") && !f.startsWith("_")).sort();
const block = files.map(f => `    <script src="widgets/${f}"></script>`).join("\n");

let html = fs.readFileSync(htmlPath, "utf-8");
const start = "<!-- widgets:start (auto-generated by test/gen-index.mjs — do not edit by hand) -->";
const end = "<!-- widgets:end -->";
const re = new RegExp(start.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + "[\\s\\S]*?" + end.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
html = html.replace(re, `${start}\n${block}\n    ${end}`);
fs.writeFileSync(htmlPath, html);
console.log(`registered ${files.length} widget files in index.html`);
